import { SentimentResult } from "@/lib/types";

interface SentimentCardProps {
  sentiment: SentimentResult;
}

const classificationConfig = {
  positive: {
    label: "Positive",
    icon: "★",
    badgeClass: "badge-positive",
    barColor: "bg-green-400",
    glow: "shadow-green-500/20",
  },
  mixed: {
    label: "Mixed",
    icon: "◈",
    badgeClass: "badge-mixed",
    barColor: "bg-yellow-400",
    glow: "shadow-yellow-500/20",
  },
  negative: {
    label: "Negative",
    icon: "✕",
    badgeClass: "badge-negative",
    barColor: "bg-red-400",
    glow: "shadow-red-500/20",
  },
};

export default function SentimentCard({ sentiment }: SentimentCardProps) {
  const config = classificationConfig[sentiment.classification];
  const score = Math.min(100, Math.max(0, sentiment.audienceScore));

  return (
    <div className="bg-cinema-card border border-cinema-border rounded-2xl p-6 space-y-6 animate-fade-up card-glow transition-all duration-300">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h2 className="font-display text-xl text-cinema-text">
          Audience Sentiment
        </h2>
        <span className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-sm font-medium ${config.badgeClass}`}>
          <span>{config.icon}</span>
          {config.label} Reception
        </span>
      </div>

      {/* Audience Score Bar */}
      <div className="space-y-2">
        <div className="flex items-center justify-between text-sm">
          <span className="text-cinema-muted">Audience Score</span>
          <span className="text-cinema-gold font-medium">{score}/100</span>
        </div>
        <div className="h-2 bg-cinema-border rounded-full overflow-hidden">
          <div
            className={`h-full ${config.barColor} rounded-full transition-all duration-1000 ease-out shadow-lg ${config.glow}`}
            style={{ width: `${score}%` }}
          />
        </div>
      </div>

      {/* AI Summary */}
      <div className="space-y-2">
        <h3 className="text-xs font-medium text-cinema-muted uppercase tracking-widest">
          AI Analysis
        </h3>
        <p className="text-cinema-text leading-relaxed text-[15px]">
          {sentiment.summary}
        </p>
      </div>

      {/* Key Themes */}
      {sentiment.keyThemes && sentiment.keyThemes.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-xs font-medium text-cinema-muted uppercase tracking-widest">
            Key Themes
          </h3>
          <div className="flex flex-wrap gap-2">
            {sentiment.keyThemes.map((theme, index) => (
              <span
                key={index}
                className="px-3 py-1.5 rounded-full text-sm border border-cinema-border
                  text-cinema-muted bg-cinema-deep hover:border-cinema-gold/30
                  hover:text-cinema-gold transition-colors duration-200"
              >
                {theme}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* AI disclaimer */}
      <p className="text-xs text-cinema-muted/60 border-t border-cinema-border pt-4">
        ✦ Analysis generated by Groq AI (LLaMA 3.1) based on publicly available ratings and metadata
      </p>
    </div>
  );
}
